(deftheme xin-cyber
  "Created 2014-01-02.")

(custom-theme-set-faces
 'xin-cyber
 '(default ((t (:family "文泉驿等宽微米黑" :foundry "unknown" :width normal :height 105 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#d3d3d3" :background "#2e3436" :stipple nil :inherit nil))))
 '(cursor ((t (:background "Gold"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#7d7c61"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#61CE3C"))))
 '(highlight ((t (:underline (:color foreground-color :style line) :inverse-video nil :foreground "#ffffff" :background "#333333"))))
 '(region ((t (:foreground "#f6f3e8" :background "black"))))
 '(shadow ((t (:foreground "#999999"))))
 '(secondary-selection ((t (:foreground "#f6f3e8" :background "#5f5f5f"))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#f2777a" :background "#ff0000"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#FF6400"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#999999" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#8B8989"))))
 '(font-lock-constant-face ((t (:foreground "#4c83ff"))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#cc99cc" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "yellow green" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "light sky blue" :weight bold))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#6699cc"))))
 '(font-lock-preprocessor-face ((t (:foreground "#919191" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#E9C062" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#ff0000" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#61CE3C"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#D8FA3C"))))
 '(font-lock-variable-name-face ((t (:foreground "#D8FA3C"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ff69b4" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :foreground "#f6f3e8" :background "#333333" :inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#ffff00"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#d0bf8f" :inherit (link)))))
 '(fringe ((t (:foreground "#bdbdb3" :background "#393939"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#ffff00" :background "#2b2b2b" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#4c83ff" :background "#333333"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "gold" :background "#000000"))))
 '(mode-line-emphasis ((t (:weight bold :slant italic :foreground "#cccccc"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#cc99cc"))))
 '(mode-line-inactive ((t (:weight normal :box (:line-width -1 :color nil :style nil) :foreground "#4D4D4D" :background "#1A1A1A" :inherit (mode-line)))))
 '(isearch ((t (:weight bold :inverse-video t :foreground "#000000" :background "#ff1493"))))
 '(isearch-fail ((t (:inverse-video t :foreground "#bdbdb3" :background "#8b0000" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:weight bold :inverse-video t :foreground "#000000" :background "#ffff00"))))
 '(match ((t (:weight bold :inverse-video t :foreground "#ff1493" :background "#000000"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:background "#333333" :inherit (isearch))))))

(provide-theme 'xin-cyber)
